### ISSUE TITLE
something went wrong with react16.7

### ISSUE THREAD

**Issue by Jemair** [SidKwok/template-rwb#46]
i want to try `hooks api` with this boilerplate but something went wrong:

i have updated `react@next` & `react-dom@next`, and i can read state from `useState`
however when i called `setState`, nothing happended, the state didn't change.

Doubting its a HMR problem, but i tried changing `export hot(module)(App)` to `export App`, didn't help

may have a look if you have time. same code runs fine on cra
thanks

**Comment by SidKwok** [comment]
It's related to this [issue](https://github.com/gaearon/react-hot-loader/issues/1088).

But you can disable `react-hot-loader` as a workaround by commenting some codes in these files:
`App.jsx`:
```diff
- import { hot } from 'react-hot-loader'
+ // import { hot } from 'react-hot-loader'
...
- // export default hot(module)(App)
+ export default App
```

`.babelrc`:
```diff
...
- "development": {
-     "plugins": ["react-hot-loader/babel"]
- }
...
```

Seems the collaborator [has already started to draft a PR](https://github.com/gaearon/react-hot-loader/issues/1088#issuecomment-433537974) for the issue, and it will be fixed in the template as soon as RHL provide the patches.
